// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NfwgN9a6ALTKjYSyviQZZvbEiqM-sL0',
    appId: '1:625907295246:web:103bafd06c516c37f4085f',
    messagingSenderId: '625907295246',
    projectId: 'solura-318fd',
    authDomain: 'solura-318fd.firebaseapp.com',
    storageBucket: 'solura-318fd.firebasestorage.app',
    measurementId: 'G-TGNE9LXC3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfh8IC_DbL8phUhbdGiH86Ykg6KGXZAc',
    appId: '1:625907295246:android:1aa6363e2ca29622f4085f',
    messagingSenderId: '625907295246',
    projectId: 'solura-318fd',
    storageBucket: 'solura-318fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYgWLwH2YVy0ysW-HhQNHzpiClhVWsrA',
    appId: '1:625907295246:ios:375b111858934aacf4085f',
    messagingSenderId: '625907295246',
    projectId: 'solura-318fd',
    storageBucket: 'solura-318fd.firebasestorage.app',
    iosBundleId: 'com.yassir.soluraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYgWLwH2YVy0ysW-HhQNHzpiClhVWsrA',
    appId: '1:625907295246:ios:71cd8d54ad3d61f9f4085f',
    messagingSenderId: '625907295246',
    projectId: 'solura-318fd',
    storageBucket: 'solura-318fd.firebasestorage.app',
    iosBundleId: 'com.example.soluraAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0NfwgN9a6ALTKjYSyviQZZvbEiqM-sL0',
    appId: '1:625907295246:web:514ee38787e6305ef4085f',
    messagingSenderId: '625907295246',
    projectId: 'solura-318fd',
    authDomain: 'solura-318fd.firebaseapp.com',
    storageBucket: 'solura-318fd.firebasestorage.app',
    measurementId: 'G-YPLBGRKWKK',
  );
}
